return function(_)
    hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
    hl.env("XDG_SESSION_DESKTOP", "Hyprland")
    hl.env("XDG_SESSION_TYPE", "wayland")
    hl.env("QT_QPA_PLATFORM", "wayland")
    hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
    hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
    hl.env("QT_QPA_PLATFORMTHEME_QT6", "gtk3")
    hl.env("XCURSOR_SIZE", "24")
    hl.env("HYPRCURSOR_SIZE", "24")
end
