return function(ctx)
    local apps = ctx.apps
    local main_mod = "SUPER"

    hl.bind(main_mod .. " + T", hl.dsp.exec_cmd(apps.terminal))
    hl.bind(main_mod .. " + C", hl.dsp.send_shortcut({ mods = "CTRL", key = "C" }))
    hl.bind(main_mod .. " + V", hl.dsp.send_shortcut({ mods = "CTRL", key = "V" }))
    hl.bind(main_mod .. " + Q", hl.dsp.window.close())
    hl.bind(main_mod .. " + M", hl.dsp.exec_cmd(apps.powermenu))
    hl.bind(main_mod .. " + E", hl.dsp.exec_cmd(apps.file_manager))
    hl.bind(main_mod .. " + F", hl.dsp.exec_cmd("hyprctl dispatch fullscreen 1"))
    hl.bind(main_mod .. " + SHIFT + F", hl.dsp.window.fullscreen({ action = "toggle" }))
    hl.bind(main_mod .. " + ALT + L", hl.dsp.exec_cmd(apps.lock))
    hl.bind(main_mod .. " + SHIFT + V", hl.dsp.window.float({ action = "toggle" }))
    hl.bind(main_mod .. " + SPACE", hl.dsp.exec_cmd(apps.explorer))
    hl.bind(main_mod .. " + SHIFT + SPACE", hl.dsp.exec_cmd(apps.launcher))
    hl.bind(main_mod .. " + O", hl.dsp.exec_cmd(apps.dashboard))
    hl.bind(main_mod .. " + W", hl.dsp.exec_cmd("hyprctl dispatch togglegroup"))
    hl.bind(main_mod .. " + MINUS", hl.dsp.layout("splitratio -0.1"))
    hl.bind(main_mod .. " + EQUAL", hl.dsp.layout("splitratio 0.1"))
    hl.bind(main_mod .. " + SHIFT + EQUAL", hl.dsp.layout("splitratio 0.1"))
    hl.bind(main_mod .. " + I", hl.dsp.layout("togglesplit"))

    hl.bind(main_mod .. " + H", hl.dsp.focus({ direction = "left" }))
    hl.bind(main_mod .. " + L", hl.dsp.focus({ direction = "right" }))
    hl.bind(main_mod .. " + K", hl.dsp.focus({ direction = "up" }))
    hl.bind(main_mod .. " + J", hl.dsp.focus({ direction = "down" }))

    hl.bind(main_mod .. " + SHIFT + H", hl.dsp.window.move({ direction = "left" }))
    hl.bind(main_mod .. " + SHIFT + L", hl.dsp.window.move({ direction = "right" }))
    hl.bind(main_mod .. " + SHIFT + K", hl.dsp.window.move({ direction = "up" }))
    hl.bind(main_mod .. " + SHIFT + J", hl.dsp.window.move({ direction = "down" }))

    for i = 1, 9 do
        local key = i % 10
        hl.bind(main_mod .. " + " .. key, hl.dsp.focus({ workspace = i }))
        hl.bind(main_mod .. " + CTRL + " .. key, hl.dsp.window.move({ workspace = i }))
        hl.bind(main_mod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
    end

    hl.bind(main_mod .. " + N", hl.dsp.focus({ workspace = "e+1" }))
    hl.bind(main_mod .. " + P", hl.dsp.focus({ workspace = "e-1" }))
    hl.bind(main_mod .. " + SHIFT + N", hl.dsp.window.move({ workspace = "e+1" }))
    hl.bind(main_mod .. " + SHIFT + P", hl.dsp.window.move({ workspace = "e-1" }))
    hl.bind(main_mod .. " + code:49", hl.dsp.focus({ workspace = "e+1" }))
    hl.bind(main_mod .. " + code:25", hl.dsp.focus({ workspace = "e-1" }))
    hl.bind(main_mod .. " + SHIFT + code:49", hl.dsp.window.move({ workspace = "e+1" }))
    hl.bind(main_mod .. " + SHIFT + code:25", hl.dsp.window.move({ workspace = "e-1" }))
    hl.bind(main_mod .. " + S", hl.dsp.workspace.toggle_special("magic"))
    hl.bind(main_mod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))
    hl.bind(main_mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
    hl.bind(main_mod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
    hl.bind(main_mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
    hl.bind(main_mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

    hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
    hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
    hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
    hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
    hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
    hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })
    hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
    hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"), { locked = true })
    hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
    hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
    hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
    hl.bind("Print", hl.dsp.exec_cmd("screenshot-snip"))
    hl.bind("CTRL + Print", hl.dsp.exec_cmd(apps.screenshot))
    hl.bind("ALT + Print", hl.dsp.exec_cmd(apps.screenshot_freeze))
end
