wallpaper {
    monitor = DP-4
    path = /home/taavi/.config/hypr/wallpapers/wallhaven-k828w6.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-5
    path = /home/taavi/.config/hypr/wallpapers/wallhaven-k828w6.jpg
    fit_mode = cover
}

splash = false
ipc = on
